# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import inspirai_fps.simple_command_pb2 as simple__command__pb2


class CommanderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Request_S2A_UpdateGame = channel.unary_unary(
                '/fps_command.Commander/Request_S2A_UpdateGame',
                request_serializer=simple__command__pb2.S2A_Request_Data.SerializeToString,
                response_deserializer=simple__command__pb2.A2S_Reply_Data.FromString,
                )


class CommanderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Request_S2A_UpdateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommanderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Request_S2A_UpdateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.Request_S2A_UpdateGame,
                    request_deserializer=simple__command__pb2.S2A_Request_Data.FromString,
                    response_serializer=simple__command__pb2.A2S_Reply_Data.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fps_command.Commander', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Commander(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Request_S2A_UpdateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fps_command.Commander/Request_S2A_UpdateGame',
            simple__command__pb2.S2A_Request_Data.SerializeToString,
            simple__command__pb2.A2S_Reply_Data.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
